name: ztdlbootcamp
channels:
- defaults
dependencies:
- python=3.7.*
- bz2file==0.98
- cython==0.29.*
- dill==0.3.*
- numpy==1.17.*
- flask==1.1.*
- gensim==3.8.*
- h5py==2.9.*
- jupyter==1.0.*
- matplotlib==3.1.*
- pandas==0.25.*
- pillow==6.2.*
- pip==19.3.*
- pytest==5.3.*
- pyhamcrest==1.9.*
- scikit-learn==0.21.*
- scipy==1.3.*
- seaborn==0.9.*
- setuptools==42.0.*
- twisted==19.10.*
- pip:
  - tensorflow==2.1.*
  - wandb==0.8.16
  - tensorflow-serving-api==2.0.*
